def test_creates_different_producers_when_multiple_columns(self):
        schema = Schema()
        schema.define_column('A', type='int')
        schema.define_column('B', type='int')
        schema.define_column('C', type='int')
        self.assertEqual(('A', 'B', 'C'), schema.columns)
        self.assertEqual(3, len(schema.producers))
        producers = sorted(schema.producers, key=lambda x: x.name)
        self.assertEqual('A', producers[0].name)
        self.assertEqual('int', producers[0].type)
        self.assertEqual({}, producers[0].config)
        self.assertEqual('B', producers[1].name)
        self.assertEqual('int', producers[1].type)
        self.assertEqual({}, producers[1].config)
        self.assertEqual('C', producers[2].name)
        self.assertEqual('int', producers[2].type)
        self.assertEqual({}, producers[2].config)